name: Deploy to AWS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install backend dependencies
        working-directory: techevince-backend
        run: npm install

      - name: Restart Backend with PM2 (Only if Running)
        run: |
          if pm2 describe backend > /dev/null 2>&1; then
            pm2 restart backend --update-env
          else
            cd ~/Techevince-2025/techevince-backend/
            pm2 start src/index.js --name backend
          fi

          pm2 save

      - name: Restart Nginx
        run: sudo systemctl restart nginx
